language: python

python:
  - '2.7'

install:
  - python setup.py install

script:
  - python setup.py test

deploy:
  - provider: releases
    skip_cleanup: true
    file_glob: true
    api_key:
      secure: L0MF+DABWi/fdTVLkkrJcpyrHBMrz6TOerQgRXk9SLrNaonAlxDDs3t3hkkOITdsSES5uXaV693a//yYKxASlMpt9Y8cZhzKsi4A/WwTf9ywukOjy/hgOfERLOL3cN87ypkCY8xZ3mxTO2EGnauEsHQicj0OCdkwezM/5nPWvHhT6mgFArZ3AxJRcUBsMueK1ZcJGwy0CcqJ0RaOM7veQO6xBAoKh6TXZWlsd+1vjQ6Su5jnj2bX+u1AMiZKWzRc0RRyUVZXk6m5o117r92Mmqy5B7XMtHLvgej8Rz8TGDyBPaLZHw8PVxnNTrBBCI1fVTcYGnDPLDDremfsTNBLHQsl8nT6BK6/Qv4GKCW1iepH1VL4cPisn0jv41FmCvbHio2GZ057F3J3D0CadJAIMaRYKcf9NI/SCbHN+jY7liNBcbaWG7U0zObwfnSt4DV8cfLjif2nBmfPMp+xC67b9fZy0d9it1d0UQf6tpQj1q3uTBJnLsb9xgzGFPcGYzvgEKZmP+3eluWBe0PRMNQPCBgT87INrv3v4l/ojbnIZP44Ws6XnZYNIt2CqxotapoPYzJwuf4abM8kAvV80DsuAGzI+PhYFLEzumE0fJqsUAjS5HUwwlDoUKWu1TTR8dYqGDZDKfEZj7Lz5v3jJok5dc9k9uYKu6RvGT9gEV74oFE=
    file: dist/*
    on:
      tags: true
      
  - provider: pypi
    skip_cleanup: true
    on:
      tags: true
    user:
      secure: TvRDQUib0bACWu3qDHKLfb4CNolSFJnPk7jFyMCL/m6Rz26qbeO2yJvQZ0rRvpTdyZgl5N8R+WbiEBOTfc82K54sTS7WfjS/r9NwjuIQ8u0xo80j71ryG+dYrJjN5GRB0oKNiY5ypSV49EHM/HwPkFYmCV8798U7nERr0L55j+d+H6sDTxeptUdrOnwe1ElhzliGXVTVbmT/m/3fsaLN2hZHtv6n7nONUJBZByc44Cz4PQSkz321vJ6xXHloX84US4zFzAjGEc4Z1mY1lozi3LDNXRDiZkRFyUBsrImhClUMiOstnlkkecffJ9Oufoe5wUHUHxUdXq+yjvXyUBluXvJBclwhL35iELyKupZH7P1coMkSrR5xr8xQQKkRz98kV3o0ZE1hlA8qCei1p2C2PmyDyoLf3uhkuwbbV9ojhygxlcFXjAQY7xuVmybYUmzyYUaVx6R/HeBq1qUtThdy8sAgLBBpqsvIzSeLRJxP2Cgcg2n075lMmNUo8WpkBwmAmeyKvg8mKV1G/+sBdwkXX1jnExgpF5G4MmCognu2dv71ybnZmAzbdUezS3jQYshKTyAXzIZSZLgom3Ulf38sX31CMlwOig/fhpq7QiaMfsVkNAOSObfpfH3fUWUnS/l2b+R24e0D8Vq6fZRPZPXQrrFlT6RveDlafVDtsRKk0wk=
    password:
      secure: YU47JHA/Me6k3+zcvEAZ4BsasZVBSSw1/igmGgHfzczLXVRrnKVNnagc7SUTqpdIBJmV9geNoaF0iNWqkzR5CmWkyxVa3IlcmLdOuva2VgMP5g1zpctyI6F0E0cdETLIhihYslXJB2qltBI6R0M0tKXk7kopcKdOX1gJpEIYIb+LSfxz2a54/P+d/hXFhvAdJ9Tl/4kp6pjSnk/WCmLvbCLx1pXJscrMk7KyE+sbNuIVeKoEzrWtEgoeWW7eG8G6UX5HyG+CXSltPmH2YJuF7/zOsxJAn62oKm1zQWu9FGYbDHm/ApjB0AoEvWbWOkuxfXEpu2yOjYY647HnwDPdjnVz6pY8XPofYfU52vrZs77nfM8hdkN/Z/n8TB4IHWafD4YHPQamegNue5rEZf0unHk/Ir4aoUNUMqjoFhymbZtWLnt7kFy5tsnLNZpgJ3IC8nNujIopIZPmKKjT8KpFa5TOgLK9YoT6M0NQZOjiY7RLU3lUqi1hr+v7/0ygcW8snBz/Tyg52elfMLucbsMbzHASs/3uo4Oj2u1ruc4bhazpJBfQR6biDGCdcNGzsL5onzn+t/Pcp7mEczULH0GQJ5nJMvkeh2WXEEL0C7wywTdRE/wmKdBdVweNaW6ln7V1w6YI9Oj7MJi/7QXYdo95tN85ZCahVWLXTh1zzUIUJUc=
